### ISSUE TITLE
Merging sslscan forks

### ISSUE THREAD

**Issue by rbsec** [DinoTools/sslscan#4]
I've also got a fork of sslscan - https://github.com/rbsec/sslscan/

From what I can see, the main advantages of yours over mine are:
- Better IPv6 support (including square bracket IP addresses)
- Ability to bind to local addresses
- Packaging support (AUR, RPM, etc)
- Better Makefiles/etc

The advantages of mine are:
- Detects TLS compression (CRIME)
- Test for TLS 1.1 and 1.2 on STARTTLS services
- Highlight SSLv2/weak/RC4/anonymous ciphers in output
- Hide certificate information by default
- Only show accepted ciphers by default (--no-failed)
- Hide supported client ciphers by default

It seems a bit pointless for there to be two different forks maintained,
since we're both adding a lot of the same features (IPv6, TLS 1.1/1.2
support, etc), so would you be interested in trying to merge the two forks? The cleaner output is a big reason behind the fork from the original, so that's something I'd be wanting to keep.

**Comment by phibos** [comment]
I have pushed my current work into the experimental "devel" branch to make the development process more transparent for others.

There are a lot of things I have worked on and that will change in the next release.
- Support for output handlers written in Python
- Add new output formats like yours
- Use cmake
- ...

I have added the TLS compression support and the support of your nice output format as a task for 1.11.

I will clean up the source code in the "devel" branch and merge it in the near future with the master branch.
