### ISSUE TITLE
Scan incomplete with server requiring client certificate

### ISSUE THREAD

**Issue by xambroz** [DinoTools/sslscan#8]
Hello,
this is repost from the enhancement request reported to Fedora distribution.
https://bugzilla.redhat.com/show_bug.cgi?id=1056650

Stephan Mueller smueller@atsec.com 2014-01-22 11:01:22 EST

Description of problem:
When using sslscan against a server that is configured to only allow requests based with a valid client SSL certificate (aka bi-directional authentication), and sslscan cannot offer such a certificate, sslscan will not report any results.

The TLS handshake agrees on the cipher as part of the Client/Server Hello and before the certificate authentication is completed. That means that for scanning a TLS server to see which ciphers are supported, there is NO need for a client certificate and even NO need for a successful TLS session establishment.

sslscan, however, seem to require a successful TLS session establishment before it reports the status on a connection. When reimplementing sslscan with a script as follows, the script will produce the intended output, whereas sslscan does not report status:

SERVER=localhost
PORT=4443
ciphers=$(openssl ciphers ALL | sed 's/:/ /g')
protos="ssl2 ssl3 tls1 tls1_1 tls1_2"

for p in $protos
do
        for c in $ciphers
        do
                openssl s_client -connect ${SERVER}:${PORT} -cipher ${c} -${p} > ${SERVER}.${c}.${p}
        done
done

Version-Release number of selected component (if applicable):

version 1.10.1 (and I guess all earlier versions)

How reproducible:
always

Steps to Reproduce:
1. Set up a server with bidirectional authentication requirement
openssl req -x509 -nodes -days 365 -newkey rsa:1024 -keyout mycert.pem -out mycert.pem
openssl s_server -accept 4443 -cert mycert.pem -Verify 1
1. sslscan localhost:4443
2. Monitor output of sslscan

Actual results:
no scan results of supported ciphers

Expected results:
scan results with supported ciphers

Additional info:
N/A

**Comment by phibos** [comment]
You are right. I have fixed the bug but it needs some testing before I'm going to publish it.

**Comment by phibos** [comment]
The bug should be fixed in the 1.10.x branch. I will release version 1.10.2 after some testing in a few days.

**Comment by xambroz** [comment]
cool

**Comment by phibos** [comment]
The bug has been fixed in the stable version some days ago and is included in the 1.10.2 release. It has also been fixed in the current master branch.

**Comment by xambroz** [comment]
thank you. works like charm :)
